# Generated by Django 4.2.20 on 2025-04-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='bild_links',
            field=models.ImageField(blank=True, upload_to='settings/', verbose_name='Bild links'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='bild_rechts',
            field=models.ImageField(blank=True, upload_to='settings/', verbose_name='Bild rechts'),
        ),
    ]
